/*
 * This file is generated by jOOQ.
 */
package com.mhc.jooq.codegen;


import com.mhc.jooq.codegen.tables.MarketingTaskDescriptor;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>marketing</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MARKETING_TASK_DESCRIPTOR_PRIMARY = Indexes0.MARKETING_TASK_DESCRIPTOR_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MARKETING_TASK_DESCRIPTOR_PRIMARY = Internal.createIndex("PRIMARY", MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR, new OrderField[] { MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.ID }, true);
    }
}
