/*
 * This file is generated by jOOQ.
 */
package com.mhc.jooq.codegen;


import com.mhc.jooq.codegen.tables.MarketingTaskDescriptor;
import com.mhc.jooq.codegen.tables.records.MarketingTaskDescriptorRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>marketing</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MarketingTaskDescriptorRecord> KEY_MARKETING_TASK_DESCRIPTOR_PRIMARY = UniqueKeys0.KEY_MARKETING_TASK_DESCRIPTOR_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MarketingTaskDescriptorRecord> KEY_MARKETING_TASK_DESCRIPTOR_PRIMARY = Internal.createUniqueKey(MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR, "KEY_marketing_task_descriptor_PRIMARY", MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.ID);
    }
}
