/*
 * This file is generated by jOOQ.
 */
package com.mhc.jooq.codegen;


import com.mhc.jooq.codegen.tables.MarketingTaskDescriptor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Marketing extends SchemaImpl {

    private static final long serialVersionUID = 158097891;

    /**
     * The reference instance of <code>marketing</code>
     */
    public static final Marketing MARKETING = new Marketing();

    /**
     * The table <code>marketing.marketing_task_descriptor</code>.
     */
    public final MarketingTaskDescriptor MARKETING_TASK_DESCRIPTOR = com.mhc.jooq.codegen.tables.MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR;

    /**
     * No further instances allowed
     */
    private Marketing() {
        super("marketing", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR);
    }
}
