/*
 * This file is generated by jOOQ.
 */
package com.mhc.jooq.codegen;


import com.mhc.jooq.codegen.tables.MarketingTaskDescriptor;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in marketing
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>marketing.marketing_task_descriptor</code>.
     */
    public static final MarketingTaskDescriptor MARKETING_TASK_DESCRIPTOR = MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR;
}
