/*
 * This file is generated by jOOQ.
 */
package com.mhc.jooq.codegen.tables.records;


import com.mhc.jooq.codegen.tables.MarketingTaskDescriptor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketingTaskDescriptorRecord extends UpdatableRecordImpl<MarketingTaskDescriptorRecord> implements Record22<String, String, String, String, String, String, String, String, String, String, String, Integer, Long, String, Long, Long, Long, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 883152941;

    /**
     * Setter for <code>marketing.marketing_task_descriptor.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.plan_id</code>.
     */
    public void setPlanId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.plan_id</code>.
     */
    public String getPlanId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.user_group_id</code>.
     */
    public void setUserGroupId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.user_group_id</code>.
     */
    public String getUserGroupId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.condition_group_id</code>.
     */
    public void setConditionGroupId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.condition_group_id</code>.
     */
    public String getConditionGroupId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.rule_type</code>.
     */
    public void setRuleType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.rule_type</code>.
     */
    public String getRuleType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.policy_id</code>.
     */
    public void setPolicyId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.policy_id</code>.
     */
    public String getPolicyId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.order_status</code>.
     */
    public void setOrderStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.order_status</code>.
     */
    public String getOrderStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.refund_status</code>.
     */
    public void setRefundStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.refund_status</code>.
     */
    public String getRefundStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.assistant_group_id</code>.
     */
    public void setAssistantGroupId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.assistant_group_id</code>.
     */
    public String getAssistantGroupId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.cover_people</code>.
     */
    public void setCoverPeople(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.cover_people</code>.
     */
    public Integer getCoverPeople() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.exec_time_ms</code>.
     */
    public void setExecTimeMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.exec_time_ms</code>.
     */
    public Long getExecTimeMs() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.finish_time_ms</code>.
     */
    public void setFinishTimeMs(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.finish_time_ms</code>.
     */
    public Long getFinishTimeMs() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.end_time_ms</code>.
     */
    public void setEndTimeMs(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.end_time_ms</code>.
     */
    public Long getEndTimeMs() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.cancel_reason</code>.
     */
    public void setCancelReason(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.cancel_reason</code>.
     */
    public String getCancelReason() {
        return (String) get(17);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.task_type</code>. 任务类型(短信SMS/淘内TB)
     */
    public void setTaskType(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.task_type</code>. 任务类型(短信SMS/淘内TB)
     */
    public String getTaskType() {
        return (String) get(18);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.sms_filter</code>. 短信风控规则(n天内不能再发送)
     */
    public void setSmsFilter(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.sms_filter</code>. 短信风控规则(n天内不能再发送)
     */
    public Integer getSmsFilter() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.tb_filter</code>. 淘宝风控规则(n天内不能再发送)
     */
    public void setTbFilter(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.tb_filter</code>. 淘宝风控规则(n天内不能再发送)
     */
    public Integer getTbFilter() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>marketing.marketing_task_descriptor.customer_id</code>. 客户号id
     */
    public void setCustomerId(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>marketing.marketing_task_descriptor.customer_id</code>. 客户号id
     */
    public Integer getCustomerId() {
        return (Integer) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<String, String, String, String, String, String, String, String, String, String, String, Integer, Long, String, Long, Long, Long, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<String, String, String, String, String, String, String, String, String, String, String, Integer, Long, String, Long, Long, Long, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.ID;
    }

    @Override
    public Field<String> field2() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.PLAN_ID;
    }

    @Override
    public Field<String> field3() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.NAME;
    }

    @Override
    public Field<String> field4() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.USER_GROUP_ID;
    }

    @Override
    public Field<String> field5() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.CONDITION_GROUP_ID;
    }

    @Override
    public Field<String> field6() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.RULE_TYPE;
    }

    @Override
    public Field<String> field7() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.POLICY_ID;
    }

    @Override
    public Field<String> field8() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.ORDER_STATUS;
    }

    @Override
    public Field<String> field9() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.REFUND_STATUS;
    }

    @Override
    public Field<String> field10() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.STATUS;
    }

    @Override
    public Field<String> field11() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.ASSISTANT_GROUP_ID;
    }

    @Override
    public Field<Integer> field12() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.COVER_PEOPLE;
    }

    @Override
    public Field<Long> field13() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.EXEC_TIME_MS;
    }

    @Override
    public Field<String> field14() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.UPDATE_BY;
    }

    @Override
    public Field<Long> field15() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.UPDATE_TIME_MS;
    }

    @Override
    public Field<Long> field16() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.FINISH_TIME_MS;
    }

    @Override
    public Field<Long> field17() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.END_TIME_MS;
    }

    @Override
    public Field<String> field18() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.CANCEL_REASON;
    }

    @Override
    public Field<String> field19() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.TASK_TYPE;
    }

    @Override
    public Field<Integer> field20() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.SMS_FILTER;
    }

    @Override
    public Field<Integer> field21() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.TB_FILTER;
    }

    @Override
    public Field<Integer> field22() {
        return MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR.CUSTOMER_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlanId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getUserGroupId();
    }

    @Override
    public String component5() {
        return getConditionGroupId();
    }

    @Override
    public String component6() {
        return getRuleType();
    }

    @Override
    public String component7() {
        return getPolicyId();
    }

    @Override
    public String component8() {
        return getOrderStatus();
    }

    @Override
    public String component9() {
        return getRefundStatus();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public String component11() {
        return getAssistantGroupId();
    }

    @Override
    public Integer component12() {
        return getCoverPeople();
    }

    @Override
    public Long component13() {
        return getExecTimeMs();
    }

    @Override
    public String component14() {
        return getUpdateBy();
    }

    @Override
    public Long component15() {
        return getUpdateTimeMs();
    }

    @Override
    public Long component16() {
        return getFinishTimeMs();
    }

    @Override
    public Long component17() {
        return getEndTimeMs();
    }

    @Override
    public String component18() {
        return getCancelReason();
    }

    @Override
    public String component19() {
        return getTaskType();
    }

    @Override
    public Integer component20() {
        return getSmsFilter();
    }

    @Override
    public Integer component21() {
        return getTbFilter();
    }

    @Override
    public Integer component22() {
        return getCustomerId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlanId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getUserGroupId();
    }

    @Override
    public String value5() {
        return getConditionGroupId();
    }

    @Override
    public String value6() {
        return getRuleType();
    }

    @Override
    public String value7() {
        return getPolicyId();
    }

    @Override
    public String value8() {
        return getOrderStatus();
    }

    @Override
    public String value9() {
        return getRefundStatus();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public String value11() {
        return getAssistantGroupId();
    }

    @Override
    public Integer value12() {
        return getCoverPeople();
    }

    @Override
    public Long value13() {
        return getExecTimeMs();
    }

    @Override
    public String value14() {
        return getUpdateBy();
    }

    @Override
    public Long value15() {
        return getUpdateTimeMs();
    }

    @Override
    public Long value16() {
        return getFinishTimeMs();
    }

    @Override
    public Long value17() {
        return getEndTimeMs();
    }

    @Override
    public String value18() {
        return getCancelReason();
    }

    @Override
    public String value19() {
        return getTaskType();
    }

    @Override
    public Integer value20() {
        return getSmsFilter();
    }

    @Override
    public Integer value21() {
        return getTbFilter();
    }

    @Override
    public Integer value22() {
        return getCustomerId();
    }

    @Override
    public MarketingTaskDescriptorRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value2(String value) {
        setPlanId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value4(String value) {
        setUserGroupId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value5(String value) {
        setConditionGroupId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value6(String value) {
        setRuleType(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value7(String value) {
        setPolicyId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value8(String value) {
        setOrderStatus(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value9(String value) {
        setRefundStatus(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value11(String value) {
        setAssistantGroupId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value12(Integer value) {
        setCoverPeople(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value13(Long value) {
        setExecTimeMs(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value14(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value15(Long value) {
        setUpdateTimeMs(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value16(Long value) {
        setFinishTimeMs(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value17(Long value) {
        setEndTimeMs(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value18(String value) {
        setCancelReason(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value19(String value) {
        setTaskType(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value20(Integer value) {
        setSmsFilter(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value21(Integer value) {
        setTbFilter(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord value22(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public MarketingTaskDescriptorRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Integer value12, Long value13, String value14, Long value15, Long value16, Long value17, String value18, String value19, Integer value20, Integer value21, Integer value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketingTaskDescriptorRecord
     */
    public MarketingTaskDescriptorRecord() {
        super(MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR);
    }

    /**
     * Create a detached, initialised MarketingTaskDescriptorRecord
     */
    public MarketingTaskDescriptorRecord(String id, String planId, String name, String userGroupId, String conditionGroupId, String ruleType, String policyId, String orderStatus, String refundStatus, String status, String assistantGroupId, Integer coverPeople, Long execTimeMs, String updateBy, Long updateTimeMs, Long finishTimeMs, Long endTimeMs, String cancelReason, String taskType, Integer smsFilter, Integer tbFilter, Integer customerId) {
        super(MarketingTaskDescriptor.MARKETING_TASK_DESCRIPTOR);

        set(0, id);
        set(1, planId);
        set(2, name);
        set(3, userGroupId);
        set(4, conditionGroupId);
        set(5, ruleType);
        set(6, policyId);
        set(7, orderStatus);
        set(8, refundStatus);
        set(9, status);
        set(10, assistantGroupId);
        set(11, coverPeople);
        set(12, execTimeMs);
        set(13, updateBy);
        set(14, updateTimeMs);
        set(15, finishTimeMs);
        set(16, endTimeMs);
        set(17, cancelReason);
        set(18, taskType);
        set(19, smsFilter);
        set(20, tbFilter);
        set(21, customerId);
    }
}
