
package com.mhc.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceImpl", targetNamespace = "http://impl.service.webservice.mhc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceImpl {


    /**
     * 
     * @return
     *     returns com.mhc.webservice.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://impl.service.webservice.mhc.com/", className = "com.mhc.webservice.client.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://impl.service.webservice.mhc.com/", className = "com.mhc.webservice.client.FindResponse")
    @Action(input = "http://impl.service.webservice.mhc.com/UserServiceImpl/findRequest", output = "http://impl.service.webservice.mhc.com/UserServiceImpl/findResponse")
    public User find();

}
